export const SHOP_ITEMS = [
  // ── 도구 (지니기 아이템) ────────────────────────────────────────────
  { id: 'tool_lifejewel',   name: '생명의구슬',    category: 'tool', emoji: '🔮', cost: 500, effect: '기술 위력 ×1.3', description: '매 턴 최대HP 1/10 감소' },
  { id: 'tool_specs',       name: '구애안경',      category: 'tool', emoji: '👓', cost: 400, effect: '특수공격 ×1.5', description: '처음 선택한 기술만 사용 가능' },
  { id: 'tool_scarf',       name: '구애스카프',    category: 'tool', emoji: '🧣', cost: 400, effect: '스피드 ×1.5',   description: '처음 선택한 기술만 사용 가능' },
  { id: 'tool_leftovers',   name: '먹다남은음식',  category: 'tool', emoji: '🍖', cost: 300, effect: 'HP 1/16 회복',  description: '매 턴 조금씩 HP 회복' },
  { id: 'tool_shellbell',   name: '조개껍질방울',  category: 'tool', emoji: '🔔', cost: 250, effect: '대미지 1/8 흡수', description: '준 대미지의 1/8 HP 회복' },
  { id: 'tool_sash',        name: '기합의띠',      category: 'tool', emoji: '🩹', cost: 250, effect: 'HP1 생존',      description: 'HP 최대시 기절타를 HP1로 버팀' },
  { id: 'tool_sludge',      name: '검은진흙',      category: 'tool', emoji: '🖤', cost: 200, effect: 'HP 1/8 회복',   description: '독 타입 전용 · 독 아니면 역효과' },
  { id: 'tool_wiseglasses', name: '박식안경',      category: 'tool', emoji: '🤓', cost: 200, effect: '특수기술 ×1.1', description: '특수 계열 기술 위력 강화' },
  { id: 'tool_spelltag',    name: '저주의부적',    category: 'tool', emoji: '👻', cost: 150, effect: '고스트 기술 ×1.2', description: '고스트 타입 기술 위력 강화' },
  { id: 'tool_poisonbarb',  name: '독바늘',        category: 'tool', emoji: '💜', cost: 150, effect: '독 기술 ×1.2',  description: '독 타입 기술 위력 강화' },

  // ── 강화 아이템 (비타민) — +10 EV / 최대 252 per stat, 510 total ──
  { id: 'vit_hp',    name: '맥스업',    category: 'vitamin', stat: 'HP',      emoji: '❤️', cost: 20, description: 'HP +10 EV' },
  { id: 'vit_atk',  name: '타우린',   category: 'vitamin', stat: '공격',    emoji: '🥩', cost: 20, description: '공격 +10 EV' },
  { id: 'vit_def',  name: '사포닌',   category: 'vitamin', stat: '방어',    emoji: '🪨', cost: 20, description: '방어 +10 EV' },
  { id: 'vit_spatk',name: '리보플라빈', category: 'vitamin', stat: '특수공격', emoji: '🧪', cost: 20, description: '특수공격 +10 EV' },
  { id: 'vit_spdef',name: '키토산',   category: 'vitamin', stat: '특수방어', emoji: '💊', cost: 20, description: '특수방어 +10 EV' },
  { id: 'vit_spd',  name: '알칼로이드', category: 'vitamin', stat: '스피드',  emoji: '⚗️', cost: 20, description: '스피드 +10 EV' },

  // ── 기술머신 ───────────────────────────────────────────────────────
  { id: 'tm01', tmNum: 'TM01', name: '힘껏펀치',     category: 'tm', moveName: '힘껏펀치',     emoji: '👊', cost: 300, moveType: '격투', moveCategory: '물리', movePower: 150 },
  { id: 'tm06', tmNum: 'TM06', name: '맹독',         category: 'tm', moveName: '맹독',         emoji: '☠️', cost: 100,  moveType: '독',   moveCategory: '변화', movePower: null },
  { id: 'tm11', tmNum: 'TM11', name: '쾌청',         category: 'tm', moveName: '쾌청',         emoji: '☀️', cost: 100,  moveType: '불꽃', moveCategory: '변화', movePower: null },
  { id: 'tm13', tmNum: 'TM13', name: '얼음빔',       category: 'tm', moveName: '얼음빔',       emoji: '❄️', cost: 200,  moveType: '얼음', moveCategory: '특수', movePower: 90 },
  { id: 'tm14', tmNum: 'TM14', name: '눈보라',       category: 'tm', moveName: '눈보라',       emoji: '🌨️', cost: 250,  moveType: '얼음', moveCategory: '특수', movePower: 110 },
  { id: 'tm15', tmNum: 'TM15', name: '기가임팩트',   category: 'tm', moveName: '기가임팩트',   emoji: '💫', cost: 300, moveType: '노말', moveCategory: '물리', movePower: 150 },
  { id: 'tm17', tmNum: 'TM17', name: '방어',         category: 'tm', moveName: '방어',         emoji: '🛡️', cost: 100,  moveType: '노말', moveCategory: '변화', movePower: null },
  { id: 'tm18', tmNum: 'TM18', name: '비바라기',     category: 'tm', moveName: '비바라기',     emoji: '🌧️', cost: 100,  moveType: '물',   moveCategory: '변화', movePower: null },
  { id: 'tm24', tmNum: 'TM24', name: '10만볼트',     category: 'tm', moveName: '10만볼트',     emoji: '⚡', cost: 200,  moveType: '전기', moveCategory: '특수', movePower: 90 },
  { id: 'tm25', tmNum: 'TM25', name: '번개',         category: 'tm', moveName: '번개',         emoji: '🌩️', cost: 250,  moveType: '전기', moveCategory: '특수', movePower: 110 },
  { id: 'tm26', tmNum: 'TM26', name: '지진',         category: 'tm', moveName: '지진',         emoji: '🌍', cost: 250,  moveType: '땅',   moveCategory: '물리', movePower: 100 },
  { id: 'tm29', tmNum: 'TM29', name: '사이코키네시스', category: 'tm', moveName: '사이코키네시스', emoji: '🔮', cost: 250, moveType: '에스퍼', moveCategory: '특수', movePower: 90 },
  { id: 'tm30', tmNum: 'TM30', name: '섀도볼',       category: 'tm', moveName: '섀도볼',       emoji: '👻', cost: 200,  moveType: '고스트', moveCategory: '특수', movePower: 80 },
  { id: 'tm35', tmNum: 'TM35', name: '화염방사',     category: 'tm', moveName: '화염방사',     emoji: '🔥', cost: 200,  moveType: '불꽃', moveCategory: '특수', movePower: 90 },
  { id: 'tm36', tmNum: 'TM36', name: '오물폭탄',     category: 'tm', moveName: '오물폭탄',     emoji: '💜', cost: 200,  moveType: '독',   moveCategory: '특수', movePower: 90 },
  { id: 'tm37', tmNum: 'TM37', name: '모래폭풍',     category: 'tm', moveName: '모래폭풍',     emoji: '🏜️', cost: 100, moveType: '바위', moveCategory: '변화', movePower: null },
  { id: 'tm44', tmNum: 'TM44', name: '잠자기',       category: 'tm', moveName: '잠자기',       emoji: '😴', cost: 100,  moveType: '에스퍼', moveCategory: '변화', movePower: null },
  { id: 'tm50', tmNum: 'TM50', name: '대폭발',       category: 'tm', moveName: '대폭발',         emoji: '💣', cost: 350, moveType: '노말', moveCategory: '물리', movePower: 250 },
  { id: 'tm52', tmNum: 'TM52', name: '기합구슬',     category: 'tm', moveName: '기합구슬',     emoji: '💥', cost: 300,  moveType: '격투', moveCategory: '특수', movePower: 120 },
  { id: 'tm53', tmNum: 'TM53', name: '에너지볼',     category: 'tm', moveName: '에너지볼',     emoji: '🌿', cost: 200,  moveType: '풀',   moveCategory: '특수', movePower: 90 },
  { id: 'tm61', tmNum: 'TM61', name: '도깨비불',     category: 'tm', moveName: '도깨비불',     emoji: '🕯️', cost: 100,  moveType: '불꽃', moveCategory: '변화', movePower: null },
  { id: 'tm65', tmNum: 'TM65', name: '악의파동',     category: 'tm', moveName: '악의파동',     emoji: '🌑', cost: 200,  moveType: '악',   moveCategory: '특수', movePower: 80 },
  { id: 'tm71', tmNum: 'TM71', name: '스톤에지',     category: 'tm', moveName: '스톤에지',     emoji: '💎', cost: 300, moveType: '바위', moveCategory: '물리', movePower: 100 },
  { id: 'tm80', tmNum: 'TM80', name: '폭포오르기',   category: 'tm', moveName: '폭포오르기',   emoji: '🌊', cost: 150, moveType: '물',   moveCategory: '물리', movePower: 80 },
  { id: 'tm85', tmNum: 'TM85', name: '꿈먹기',       category: 'tm', moveName: '꿈먹기',       emoji: '💭', cost: 250,  moveType: '에스퍼', moveCategory: '특수', movePower: 100 },
  { id: 'tm87', tmNum: 'TM87', name: '뽐내기',     category: 'tm', moveName: '뽐내기',     emoji: '😤', cost: 100,  moveType: '노말', moveCategory: '변화', movePower: null },
  { id: 'tm90', tmNum: 'TM90', name: '대체',         category: 'tm', moveName: '대체',         emoji: '🪆', cost: 200,  moveType: '노말', moveCategory: '변화', movePower: null },
  { id: 'tm91', tmNum: 'TM91', name: '고드름침',     category: 'tm', moveName: '고드름침',     emoji: '🧊', cost: 200, moveType: '얼음', moveCategory: '물리', movePower: 25 },
  { id: 'tm94', tmNum: 'TM94', name: '바위깨기',     category: 'tm', moveName: '바위깨기',     emoji: '🔨', cost: 100, moveType: '격투', moveCategory: '물리', movePower: 40 },
]
