// sleep/6-anims.js — pixel art (auto-converted from 32×27)
const _ = null

export const COLORS = {
  outline: '#353535',
  body: '#336D5F',
  bodyL: '#5D5D5D',
  bodyD: '#CA4033',
  belly: '#4A8374',
  shadow: '#D65F3F',
  accent: '#FC5832',
  highlight: '#D38545',
  detail1: '#F48F27',
  detail2: '#D5B05F',
  detail3: '#FCDA30',
  detail4: '#F4D26E',
  detail5: '#C0C0C0',
  detail6: '#FEFEFE',
}

// grid: 32×27
export const BASE_BODY = [
/* row  0 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  1 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', 'accent', 'bodyD', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  2 */ [_, _, _, _, _, 'outline', _, _, _, _, _, _, _, _, 'bodyD', 'detail1', 'accent', 'bodyD', _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  3 */ [_, _, _, _, 'outline', 'shadow', 'outline', _, 'outline', _, _, _, _, _, _, 'accent', 'detail1', 'accent', _, 'outline', _, _, _, _, _, _, _, _, _, _, _, _],
/* row  4 */ [_, _, _, _, 'outline', 'shadow', 'detail6', 'outline', 'detail1', 'outline', _, _, _, _, 'bodyD', 'detail1', 'detail1', 'detail3', 'outline', 'detail1', 'outline', _, _, _, _, _, _, _, _, _, _, _],
/* row  5 */ [_, _, _, 'outline', 'shadow', 'bodyL', 'outline', 'detail1', 'shadow', 'outline', 'outline', _, _, _, 'bodyD', 'detail1', 'detail3', 'detail1', 'bodyD', 'outline', 'detail1', 'outline', 'outline', _, _, _, _, _, _, _, _, _],
/* row  6 */ [_, _, _, 'outline', 'detail1', 'shadow', 'shadow', 'detail1', 'outline', 'detail1', 'detail1', 'outline', 'outline', _, _, 'bodyD', 'detail1', 'outline', 'detail6', 'outline', 'detail1', 'detail1', 'detail1', 'outline', _, _, _, _, _, _, _, _],
/* row  7 */ [_, _, 'outline', 'shadow', 'detail1', 'detail1', 'detail1', 'detail1', 'shadow', 'detail1', 'detail1', 'detail1', 'detail1', 'outline', _, _, 'outline', 'shadow', 'outline', 'detail1', 'bodyL', 'body', 'bodyL', 'detail1', 'outline', _, _, _, _, _, _, _],
/* row  8 */ [_, 'outline', 'shadow', 'detail1', 'detail1', 'detail1', 'detail1', 'detail1', 'detail1', 'shadow', 'shadow', 'detail1', 'detail1', 'detail1', 'outline', _, 'outline', 'outline', 'detail1', 'bodyL', 'body', 'body', 'belly', 'bodyL', 'detail1', 'outline', _, _, _, _, _, _],
/* row  9 */ [_, 'outline', 'outline', 'detail1', 'detail1', 'detail1', 'outline', 'detail1', 'shadow', 'outline', 'shadow', 'shadow', 'detail1', 'detail1', 'detail1', 'outline', 'detail1', 'shadow', 'bodyL', 'body', 'belly', 'body', 'belly', 'belly', 'bodyL', 'detail1', 'outline', _, _, _, _, _],
/* row 10 */ ['outline', 'shadow', 'outline', 'shadow', 'detail1', 'outline', 'detail1', 'shadow', 'outline', 'body', 'outline', 'shadow', 'shadow', 'detail1', 'detail1', 'detail1', 'bodyL', 'bodyL', 'body', 'body', 'belly', 'belly', 'bodyL', 'belly', 'belly', 'bodyL', 'detail1', 'outline', _, _, _, _],
/* row 11 */ ['outline', 'shadow', 'outline', 'detail1', 'detail1', 'detail1', 'shadow', 'outline', 'body', 'outline', 'outline', 'shadow', 'shadow', 'detail1', 'detail1', 'detail1', 'detail1', 'outline', 'body', 'body', 'body', 'belly', 'belly', 'bodyL', 'belly', 'belly', 'bodyL', 'detail1', 'outline', _, _, _],
/* row 12 */ ['outline', 'outline', 'detail1', 'detail1', 'detail1', 'shadow', 'outline', 'detail6', 'outline', 'shadow', 'bodyL', 'detail1', 'detail1', 'detail1', 'bodyL', 'detail1', 'detail1', 'detail1', 'bodyL', 'outline', 'outline', 'outline', 'outline', 'bodyL', 'belly', 'belly', 'body', 'detail1', 'outline', _, _, _],
/* row 13 */ ['outline', 'shadow', 'outline', 'detail1', 'shadow', 'outline', _, 'outline', 'shadow', 'bodyL', 'detail1', 'bodyL', 'bodyL', 'detail1', 'bodyL', 'detail1', 'bodyL', 'detail1', 'outline', 'detail6', 'detail6', 'outline', 'shadow', 'outline', 'belly', 'belly', 'belly', 'bodyL', 'detail1', 'outline', _, _],
/* row 14 */ [_, 'outline', 'body', 'outline', 'outline', _, _, 'outline', 'shadow', 'detail1', 'bodyL', 'detail1', 'detail1', 'bodyL', 'detail1', 'shadow', 'outline', 'detail1', 'shadow', 'outline', 'detail6', 'outline', 'shadow', 'shadow', 'outline', 'outline', 'belly', 'bodyL', 'detail1', 'outline', _, _],
/* row 15 */ [_, 'outline', 'shadow', 'outline', _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'detail1', 'detail1', 'shadow', 'outline', 'detail1', 'detail1', 'detail1', 'shadow', 'outline', 'shadow', 'shadow', 'shadow', 'shadow', 'bodyL', 'outline', 'bodyL', 'detail1', 'outline', _, _],
/* row 16 */ [_, _, 'outline', 'outline', _, _, 'outline', 'outline', 'outline', 'highlight', 'detail4', 'detail4', 'outline', 'outline', 'outline', 'detail1', 'detail1', 'detail1', 'detail1', 'shadow', 'bodyL', 'shadow', 'shadow', 'shadow', 'shadow', 'outline', 'detail6', 'outline', 'detail1', 'outline', _, _],
/* row 17 */ [_, _, _, _, _, 'outline', 'detail1', 'detail1', 'bodyL', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'detail1', 'bodyL', 'detail1', 'detail1', 'bodyL', 'shadow', 'shadow', 'shadow', 'shadow', 'outline', 'detail6', 'outline', 'shadow', 'outline', _, _],
/* row 18 */ [_, _, _, _, 'outline', 'outline', 'detail1', 'shadow', 'bodyL', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'bodyL', 'detail1', 'detail1', 'detail1', 'detail1', 'bodyL', 'shadow', 'shadow', 'detail2', 'outline', 'detail6', 'detail6', 'outline', _, _, _],
/* row 19 */ [_, _, _, 'outline', 'detail6', 'detail5', 'bodyL', 'shadow', 'bodyL', 'detail2', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'bodyL', 'detail1', 'detail1', 'detail1', 'detail1', 'bodyL', 'shadow', 'detail2', 'outline', 'detail5', 'detail5', 'detail5', _, _, _, _],
/* row 20 */ [_, _, 'outline', 'detail6', 'bodyL', 'detail1', 'detail1', 'shadow', 'bodyL', 'detail2', 'detail2', 'detail4', 'detail4', 'detail4', 'detail4', 'bodyL', 'detail1', 'detail1', 'detail1', 'detail1', 'shadow', 'bodyL', 'detail2', 'outline', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', _, _, _],
/* row 21 */ [_, _, _, 'outline', 'detail1', 'detail4', 'detail4', 'shadow', 'shadow', 'bodyL', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyL', 'bodyL', 'shadow', 'bodyL', 'shadow', 'shadow', 'bodyL', 'outline', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', _, _],
/* row 22 */ [_, _, _, _, 'outline', 'detail1', 'detail4', 'detail4', 'shadow', 'shadow', 'outline', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyL', 'detail6', 'bodyL', 'detail6', 'bodyL', 'shadow', 'outline', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', _, 'detail5', 'detail5', _, _],
/* row 23 */ [_, _, _, _, 'detail5', 'outline', 'detail1', 'detail4', 'shadow', 'outline', 'detail5', 'outline', 'outline', 'outline', 'bodyL', 'shadow', 'detail1', 'detail1', 'bodyL', 'detail6', 'outline', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', _, _, 'detail5', _, _, _],
/* row 24 */ [_, _, _, _, _, 'detail5', 'outline', 'outline', 'outline', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', 'outline', 'detail4', 'detail4', 'detail4', 'detail1', 'outline', 'detail5', 'detail5', 'detail5', 'detail5', _, _, _, _, _, _, _, _],
/* row 25 */ [_, _, _, _, _, _, 'detail5', 'detail5', 'detail5', 'detail5', _, 'detail5', 'detail5', 'detail5', 'outline', 'detail1', 'detail4', 'detail1', 'outline', 'detail5', 'detail5', 'detail5', _, _, _, _, _, _, _, _, _, _],
/* row 26 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'detail5', 'detail5', _, _, _, _, _, _, _, _, _, _, _, _],
]
