// 피죤투(18) — pixel art
const _ = null

export const COLORS = {
  outline: '#191919',
  body: '#525252',
  bodyL: '#BD3A21',
  bodyD: '#9C5A3A',
  belly: '#BD7342',
  shadow: '#BDA519',
  accent: '#EF6342',
  highlight: '#DE9C29',
  detail1: '#C5737B',
  detail2: '#EFDE10',
  detail3: '#CEBD63',
  detail4: '#E6A5A5',
  detail5: '#BDBDBD',
  detail6: '#EFDE84',
  detail7: '#FFFFFF',
}

// grid: 32x29
export const BASE_BODY = [
/* row  0 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', _, _, _, _],
/* row  1 */ [_, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'detail4', 'detail4', 'bodyL', 'outline', 'outline', _, _],
/* row  2 */ [_, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'detail4', 'detail4', 'bodyL', 'outline', 'outline', _, _],
/* row  3 */ [_, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'outline', 'outline', 'outline', _, 'outline', 'outline', 'detail4', 'detail4', 'bodyL', 'bodyL', 'accent', 'detail4', 'detail4', 'outline', 'outline', _, _],
/* row  4 */ [_, _, _, _, 'outline', 'outline', 'bodyL', 'bodyL', 'detail2', 'detail2', 'detail2', 'detail2', 'shadow', 'shadow', 'shadow', 'shadow', 'shadow', 'detail2', 'outline', 'body', 'body', 'accent', 'accent', 'bodyL', 'bodyL', 'accent', 'accent', 'bodyL', 'detail4', 'detail4', 'outline', _],
/* row  5 */ [_, _, _, 'outline', 'accent', 'bodyL', 'detail2', 'detail2', 'detail2', 'shadow', 'shadow', 'shadow', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'shadow', 'shadow', 'shadow', 'shadow', 'body', 'accent', 'bodyL', 'bodyL', 'accent', 'accent', 'bodyL', 'accent', 'accent', 'detail4', 'outline'],
/* row  6 */ [_, _, _, 'outline', 'accent', 'shadow', 'detail2', 'detail2', 'shadow', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'body', 'body', 'body', 'accent', 'bodyL', 'accent', 'accent', 'accent', 'bodyL', 'accent', 'accent', 'accent', 'accent', 'outline'],
/* row  7 */ [_, _, _, 'outline', 'accent', 'shadow', 'detail2', 'detail2', 'shadow', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'body', 'body', 'body', 'accent', 'bodyL', 'accent', 'accent', 'accent', 'bodyL', 'accent', 'accent', 'accent', 'accent', 'outline'],
/* row  8 */ [_, 'outline', 'outline', 'accent', 'shadow', 'detail2', 'shadow', 'shadow', 'detail2', 'detail2', 'bodyL', 'bodyL', 'bodyL', 'accent', 'accent', 'accent', 'accent', 'accent', 'body', 'accent', 'accent', 'accent', 'bodyL', 'accent', 'accent', 'accent', 'bodyL', 'accent', 'accent', 'accent', 'outline', _],
/* row  9 */ [_, 'outline', 'outline', 'accent', 'shadow', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyL', 'accent', 'accent', 'accent', 'accent', 'body', 'outline', 'outline', 'bodyL', 'accent', 'body', 'body', 'bodyD', 'bodyD', 'accent', 'accent', 'bodyL', 'accent', 'accent', 'outline', 'outline', _, _],
/* row 10 */ [_, 'outline', 'outline', 'accent', 'detail2', 'detail2', 'detail2', 'detail2', 'shadow', 'accent', 'accent', 'accent', 'body', 'body', 'outline', 'detail7', 'detail7', 'outline', 'bodyL', 'body', 'body', 'body', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'body', 'outline', _, _, _, _],
/* row 11 */ [_, 'outline', 'outline', 'accent', 'detail2', 'detail2', 'detail2', 'detail2', 'shadow', 'accent', 'accent', 'accent', 'body', 'body', 'outline', 'detail7', 'detail7', 'outline', 'bodyL', 'body', 'body', 'body', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'body', 'outline', _, _, _, _],
/* row 12 */ [_, _, _, 'outline', 'detail2', 'detail2', 'shadow', 'shadow', 'accent', 'accent', 'body', 'body', 'body', 'belly', 'belly', 'outline', 'outline', 'belly', 'body', 'bodyL', 'bodyL', 'bodyL', 'body', 'bodyD', 'bodyD', 'bodyD', 'body', 'outline', 'outline', 'outline', 'outline', _],
/* row 13 */ [_, _, _, 'outline', 'body', 'detail2', 'accent', 'accent', 'body', 'outline', 'detail5', 'detail5', 'body', 'body', 'belly', 'belly', 'belly', 'body', 'body', 'body', 'body', 'body', 'bodyD', 'bodyD', 'bodyD', 'body', 'body', 'detail6', 'detail6', 'detail6', 'detail6', 'outline'],
/* row 14 */ [_, 'outline', 'outline', 'detail4', 'detail4', 'body', 'body', 'body', 'detail5', 'outline', 'detail7', 'detail7', 'body', 'body', 'body', 'belly', 'belly', 'belly', 'highlight', 'highlight', 'highlight', 'body', 'body', 'body', 'body', 'detail6', 'detail6', 'detail6', 'body', 'body', 'body', 'outline'],
/* row 15 */ ['outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'body', 'body', 'body', 'detail3', 'detail3', 'detail3', 'detail6', 'body', 'body', 'belly', 'belly', 'highlight', 'belly', 'bodyD', 'bodyD', 'highlight', 'highlight', 'detail6', 'detail6', 'detail6', 'body', 'body', 'detail3', 'detail3', 'outline', _],
/* row 16 */ ['outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'body', 'body', 'body', 'detail3', 'detail3', 'detail3', 'detail6', 'body', 'body', 'belly', 'belly', 'highlight', 'belly', 'bodyD', 'bodyD', 'highlight', 'highlight', 'detail6', 'detail6', 'detail6', 'body', 'body', 'detail3', 'detail3', 'outline', _],
/* row 17 */ ['outline', 'detail4', 'detail4', 'detail1', 'body', 'body', 'detail1', 'detail1', 'body', 'detail6', 'detail6', 'detail6', 'detail6', 'body', 'highlight', 'highlight', 'highlight', 'belly', 'highlight', 'highlight', 'highlight', 'highlight', 'highlight', 'highlight', 'highlight', 'detail6', 'detail3', 'detail3', 'detail3', 'detail3', 'outline', _],
/* row 18 */ [_, 'outline', 'outline', 'body', 'body', 'body', 'detail1', 'detail1', 'body', 'detail6', 'detail6', 'detail6', 'detail6', 'belly', 'highlight', 'bodyD', 'bodyD', 'highlight', 'highlight', 'highlight', 'highlight', 'highlight', 'detail6', 'detail6', 'detail6', 'detail3', 'body', 'body', 'outline', 'outline', _, _],
/* row 19 */ [_, _, _, 'outline', 'outline', 'detail1', 'body', 'body', 'detail3', 'detail3', 'detail6', 'detail6', 'detail6', 'detail6', 'belly', 'body', 'body', 'highlight', 'highlight', 'highlight', 'highlight', 'belly', 'belly', 'detail3', 'detail3', 'detail3', 'detail3', 'outline', _, _, _, _],
/* row 20 */ [_, _, _, 'outline', 'outline', 'detail1', 'body', 'body', 'detail3', 'detail3', 'detail6', 'detail6', 'detail6', 'detail6', 'belly', 'body', 'body', 'highlight', 'highlight', 'highlight', 'highlight', 'belly', 'belly', 'detail3', 'detail3', 'detail3', 'detail3', 'outline', _, _, _, _],
/* row 21 */ [_, _, _, _, _, 'outline', 'outline', 'outline', 'body', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'body', 'body', 'body', 'belly', 'belly', 'belly', 'belly', 'belly', 'detail3', 'detail3', 'detail3', 'detail3', 'outline', _, _, _, _],
/* row 22 */ [_, _, _, _, _, _, _, _, 'outline', 'body', 'body', 'body', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'body', 'body', 'belly', 'belly', 'belly', 'detail3', 'detail3', 'detail3', 'outline', 'outline', _, _, _, _, _],
/* row 23 */ [_, _, _, _, _, _, 'outline', 'outline', 'detail5', 'bodyD', 'bodyD', 'bodyD', 'outline', 'body', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'body', 'body', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, _],
/* row 24 */ [_, _, _, _, _, _, 'outline', 'outline', 'detail5', 'bodyD', 'bodyD', 'bodyD', 'outline', 'body', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'body', 'body', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, _],
/* row 25 */ [_, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', 'detail7', 'outline', 'detail1', 'bodyD', 'bodyD', 'bodyD', 'detail3', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _],
/* row 26 */ [_, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'detail7', 'bodyD', 'detail1', 'detail1', 'detail1', 'outline', _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row 27 */ [_, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'body', 'detail7', 'detail7', 'outline', _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row 28 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
]

export const SLEEP_COLORS = {
  outline: '#191919',
  body: '#241407',
  bodyL: '#4E2D1C',
  bodyD: '#333333',
  belly: '#714941',
  shadow: '#545454',
  accent: '#796A31',
  highlight: '#BB3B22',
  detail1: '#98583C',
  detail2: '#AB7711',
  detail3: '#BB7140',
  detail4: '#BBA31B',
  detail5: '#EA6043',
  detail6: '#DA9627',
  detail7: '#BF7075',
  detail8: '#E8D70D',
  detail9: '#C9B85E',
  detail10: '#CBC082',
  c18: '#E19FA0',
  c19: '#EAD97D',
  c20: '#DFC0BE',
  c21: '#EFE4A4',
}

// grid: 32x29
export const SLEEP_BODY = [
/* row  0 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', 'bodyD', 'bodyD', _, _, _, _],
/* row  1 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', 'bodyD', 'body', 'c18', 'c18', 'highlight', 'bodyD', 'bodyD', _, _],
/* row  2 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', 'bodyD', 'body', 'c18', 'c18', 'highlight', 'bodyD', 'bodyD', _, _],
/* row  3 */ [_, _, _, _, _, _, 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'bodyD', _, _, _, _, _, _, _, _, 'bodyD', 'c18', 'highlight', 'highlight', 'detail5', 'c18', 'c18', 'bodyD', 'bodyD', _, _],
/* row  4 */ [_, _, _, _, 'bodyD', 'bodyD', 'highlight', 'highlight', 'detail8', 'detail8', 'detail4', 'detail4', 'detail4', 'bodyD', 'bodyD', _, _, _, _, _, _, 'bodyD', 'detail5', 'highlight', 'highlight', 'detail5', 'detail5', 'highlight', 'c18', 'c18', 'bodyD', _],
/* row  5 */ [_, _, _, 'bodyD', 'detail5', 'highlight', 'detail8', 'detail8', 'detail8', 'detail4', 'detail8', 'detail8', 'detail8', 'detail8', 'detail4', 'accent', 'bodyD', _, _, _, _, 'bodyD', 'detail5', 'highlight', 'highlight', 'detail5', 'detail5', 'highlight', 'detail5', 'detail5', 'c18', 'bodyD'],
/* row  6 */ [_, 'shadow', 'shadow', 'detail5', 'detail5', 'detail8', 'detail8', 'detail8', 'detail4', 'detail8', 'highlight', 'highlight', 'highlight', 'highlight', 'highlight', 'detail6', 'detail4', 'shadow', _, _, _, 'bodyD', 'highlight', 'detail5', 'detail5', 'detail5', 'highlight', 'detail5', 'detail5', 'detail5', 'detail5', 'bodyD'],
/* row  7 */ [_, 'bodyD', 'bodyD', 'detail5', 'detail5', 'detail8', 'detail8', 'detail8', 'detail4', 'detail8', 'highlight', 'highlight', 'highlight', 'highlight', 'highlight', 'detail6', 'detail4', 'bodyD', _, _, _, 'bodyD', 'highlight', 'detail5', 'detail5', 'detail5', 'highlight', 'detail5', 'detail5', 'detail5', 'detail5', 'bodyD'],
/* row  8 */ [_, 'bodyD', 'bodyD', 'detail5', 'detail4', 'detail8', 'detail4', 'detail4', 'detail8', 'highlight', 'detail5', 'detail5', 'detail5', 'detail5', 'detail5', 'highlight', 'highlight', 'highlight', 'bodyD', 'bodyD', 'bodyD', 'shadow', 'highlight', 'detail5', 'detail5', 'detail5', 'highlight', 'detail5', 'detail5', 'detail5', 'bodyD', _],
/* row  9 */ ['bodyD', 'detail5', 'detail5', 'detail5', 'detail8', 'detail4', 'detail8', 'detail8', 'highlight', 'detail5', 'detail5', 'detail5', 'shadow', 'shadow', 'shadow', 'detail3', 'detail5', 'detail5', 'shadow', 'detail6', 'detail6', 'detail3', 'shadow', 'shadow', 'belly', 'highlight', 'detail5', 'detail5', 'bodyD', 'bodyD', _, _],
/* row 10 */ ['bodyD', 'detail5', 'detail5', 'detail4', 'detail8', 'detail4', 'highlight', 'highlight', 'detail5', 'detail5', 'shadow', 'shadow', 'detail1', 'detail3', 'detail3', 'bodyL', 'bodyD', 'shadow', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'detail3', 'detail7', 'shadow', 'detail5', 'bodyD', _, _, _, _],
/* row 11 */ ['bodyD', 'detail5', 'detail5', 'detail4', 'detail8', 'detail4', 'highlight', 'highlight', 'detail5', 'detail5', 'shadow', 'shadow', 'detail1', 'detail3', 'detail3', 'bodyL', 'bodyD', 'shadow', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'detail3', 'detail7', 'shadow', 'detail5', 'bodyD', _, _, _, _],
/* row 12 */ ['bodyD', 'detail5', 'detail5', 'detail4', 'detail8', 'detail4', 'highlight', 'highlight', 'detail5', 'shadow', 'detail1', 'detail1', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'shadow', 'detail3', 'detail6', 'detail6', 'detail6', 'detail6', 'detail3', 'detail3', 'detail3', 'bodyD', _, _, _, _, _],
/* row 13 */ [_, 'bodyD', 'bodyD', 'detail4', 'detail8', 'highlight', 'detail5', 'detail5', 'shadow', 'detail3', 'detail3', 'detail3', 'shadow', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail6', 'detail6', 'detail6', 'detail6', 'detail3', 'detail3', 'detail3', 'detail3', 'bodyD', _, _, _, _, _],
/* row 14 */ [_, 'bodyD', 'bodyD', 'shadow', 'shadow', 'detail5', 'shadow', 'shadow', 'detail3', 'detail3', 'bodyD', 'bodyD', 'shadow', 'shadow', 'detail3', 'detail3', 'detail3', 'detail3', 'detail6', 'detail3', 'detail3', 'detail1', 'detail1', 'shadow', 'shadow', 'shadow', 'c19', 'bodyD', 'bodyD', 'bodyD', _, _],
/* row 15 */ [_, 'bodyD', 'bodyD', 'detail7', 'c18', 'bodyL', 'detail3', 'detail3', 'body', 'body', 'c21', 'c21', 'c21', 'shadow', 'detail3', 'detail3', 'detail3', 'detail1', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'c21', 'c21', 'c21', 'body', 'c21', 'c21', 'c21', 'outline', _],
/* row 16 */ [_, 'bodyD', 'bodyD', 'detail7', 'c18', 'shadow', 'detail3', 'detail3', 'bodyD', 'bodyD', 'c19', 'c19', 'c19', 'shadow', 'detail3', 'detail3', 'detail3', 'detail1', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'c19', 'c19', 'c19', 'shadow', 'c19', 'c19', 'c19', 'bodyD', _],
/* row 17 */ [_, 'bodyD', 'bodyD', 'c18', 'c18', 'c18', 'shadow', 'shadow', 'c19', 'c19', 'c19', 'c19', 'c19', 'shadow', 'detail3', 'detail1', 'detail1', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'detail2', 'c19', 'c19', 'c19', 'shadow', 'shadow', 'bodyD', _],
/* row 18 */ [_, 'bodyD', 'bodyD', 'c18', 'shadow', 'detail7', 'shadow', 'shadow', 'detail9', 'c19', 'c19', 'c19', 'shadow', 'detail3', 'detail3', 'belly', 'shadow', 'detail6', 'detail6', 'detail6', 'detail6', 'detail6', 'c19', 'c19', 'c19', 'c19', 'c19', 'shadow', 'detail9', 'detail9', 'bodyD', _],
/* row 19 */ [_, _, _, 'bodyD', 'bodyD', 'shadow', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail3', 'detail3', 'c19', 'belly', 'shadow', 'detail6', 'detail6', 'detail6', 'detail6', 'detail3', 'detail3', 'c19', 'c19', 'detail9', 'shadow', 'detail9', 'bodyD', 'bodyD', _, _],
/* row 20 */ [_, _, _, 'bodyD', 'bodyD', 'shadow', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail3', 'detail3', 'c19', 'belly', 'shadow', 'detail6', 'detail6', 'detail6', 'detail6', 'detail3', 'detail3', 'c19', 'c19', 'detail9', 'shadow', 'detail9', 'bodyD', 'bodyD', _, _],
/* row 21 */ [_, _, _, _, _, 'bodyD', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'c19', 'c19', 'c19', 'belly', 'shadow', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail9', 'detail9', 'detail9', 'detail9', 'bodyD', _, _, _, _],
/* row 22 */ [_, _, _, _, _, _, 'shadow', 'bodyD', 'detail9', 'c19', 'c19', 'c19', 'c19', 'c19', 'detail9', 'detail9', 'detail9', 'shadow', 'detail3', 'detail3', 'detail3', 'detail3', 'detail9', 'detail9', 'detail10', 'bodyD', 'bodyD', _, _, _, _, _],
/* row 23 */ [_, _, _, _, _, 'bodyD', 'detail7', 'detail7', 'shadow', 'shadow', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'detail9', 'shadow', 'shadow', 'shadow', 'shadow', 'bodyD', 'bodyD', 'outline', _, _, _, _, _, _, _],
/* row 24 */ [_, _, _, _, _, 'bodyD', 'detail7', 'detail7', 'bodyD', 'shadow', 'detail10', 'detail10', 'detail9', 'detail10', 'detail10', 'detail10', 'detail10', 'detail10', 'shadow', 'shadow', 'shadow', 'shadow', 'outline', 'outline', 'outline', _, _, _, _, _, _, _],
/* row 25 */ [_, _, _, _, _, 'bodyD', 'bodyD', 'bodyD', 'c18', 'detail1', 'bodyD', 'bodyD', 'bodyD', 'shadow', 'shadow', 'shadow', 'shadow', 'shadow', 'detail7', 'detail7', 'detail7', 'bodyD', _, _, _, _, _, _, _, _, _, _],
/* row 26 */ [_, _, _, _, _, _, 'bodyD', 'bodyD', 'bodyD', 'bodyD', _, _, 'bodyD', 'c18', 'detail1', 'detail7', 'detail7', 'detail7', 'bodyD', 'bodyD', 'bodyD', 'bodyD', _, _, _, _, _, _, _, _, _, _],
/* row 27 */ [_, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', 'bodyD', 'bodyD', 'c20', 'c18', 'bodyD', _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row 28 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, 'bodyD', 'bodyD', 'bodyD', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
]
