// 꼬부기(Squirtle) — pixel art (auto-converted from 25×20)
const _ = null

export const COLORS = {
  outline: '#191919',
  shellVD: '#7C3A0B',
  grayD: '#525252',
  shellD: '#8C5229',
  bodyD: '#3A736B',
  shellM: '#766843',
  shell: '#BD6B21',
  darkGray: '#6B7C6A',
  tan2: '#978556',
  teal: '#529C9C',
  shellL: '#D68C29',
  tan: '#AEA572',
  bellyM: '#CEAD5A',
  bodyM: '#64B3CF',
  gray: '#A6A6A6',
  belly: '#E0C670',
  bodyL: '#73C5F7',
  grayL: '#BDBDBD',
  bellyL: '#F7E68C',
  grayVL: '#DADADA',
  white: '#FFFFFF',
}

// grid: 25×20
export const BASE_BODY = [
/* row  0 */ [_, _, _, _, 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', _, _],
/* row  1 */ [_, _, 'outline', 'outline', 'teal', 'bodyL', 'bodyL', 'bodyL', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, 'outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'outline', _],
/* row  2 */ [_, 'outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyM', 'teal', 'outline', 'outline', _, _, _, _, 'outline', 'bodyL', 'bodyL', 'bodyL', 'teal', 'teal', 'teal', 'outline'],
/* row  3 */ [_, 'outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyM', 'teal', 'outline', 'outline', _, _, _, _, 'outline', 'bodyL', 'bodyL', 'bodyL', 'teal', 'teal', 'teal', 'outline'],
/* row  4 */ [_, 'outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'grayD', 'shell', 'outline', 'outline', _, _, 'outline', 'bodyL', 'bodyL', 'teal', 'grayD', 'grayD', 'bodyD', 'outline'],
/* row  5 */ ['outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'teal', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'teal', 'grayD', 'shellL', 'shell', 'outline', 'outline', 'teal', 'bodyL', 'teal', 'grayD', 'teal', 'teal', 'teal', 'outline'],
/* row  6 */ ['outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'bodyD', 'white', 'outline', 'bodyL', 'bodyL', 'bodyL', 'teal', 'grayD', 'shellD', 'shellL', 'shell', 'shell', 'grayD', 'teal', 'teal', 'grayD', 'teal', 'teal', 'outline', _],
/* row  7 */ ['outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'teal', 'outline', 'outline', 'bodyL', 'bodyM', 'teal', 'teal', 'grayD', 'white', 'shellD', 'shellL', 'shellL', 'grayD', 'teal', 'teal', 'grayD', 'outline', 'outline', _, _],
/* row  8 */ [_, 'outline', 'bodyL', 'bodyL', 'bodyL', 'bodyL', 'outline', 'shellD', 'teal', 'teal', 'teal', 'grayD', 'grayL', 'white', 'shellD', 'shellL', 'shellL', 'shell', 'grayD', 'teal', 'outline', _, _, _, _],
/* row  9 */ [_, 'gray', 'bodyD', 'bodyD', 'teal', 'bodyM', 'bodyD', 'darkGray', 'teal', 'teal', 'bodyD', 'bodyD', 'darkGray', 'grayVL', 'grayL', 'shell', 'shell', 'shell', 'grayD', 'teal', 'outline', _, _, _, _],
/* row 10 */ [_, _, 'outline', 'outline', 'grayD', 'teal', 'teal', 'teal', 'teal', 'bodyD', 'grayD', 'teal', 'grayD', 'grayL', 'white', 'shellVD', 'shellD', 'shell', 'grayD', 'teal', 'outline', _, _, _, _],
/* row 11 */ [_, _, 'outline', 'outline', 'teal', 'grayD', 'grayD', 'grayD', 'bellyM', 'belly', 'bellyL', 'grayD', 'bodyL', 'grayD', 'white', 'shellVD', 'shellD', 'shellD', 'grayD', 'outline', _, _, _, _, _],
/* row 12 */ [_, _, _, _, 'outline', 'outline', 'bellyL', 'bellyL', 'bellyL', 'tan', 'grayD', 'bodyL', 'bodyL', 'bodyL', 'grayD', 'shellD', 'shellD', 'shell', 'outline', _, _, _, _, _, _],
/* row 13 */ [_, _, _, _, _, _, 'outline', 'bellyM', 'bellyM', 'tan2', 'grayD', 'bodyL', 'bodyL', 'teal', 'grayD', 'shellD', 'shellD', 'shell', 'outline', _, _, _, _, _, _],
/* row 14 */ [_, _, _, _, _, 'outline', 'bodyD', 'grayD', 'bellyL', 'bellyL', 'bellyL', 'grayD', 'teal', 'grayD', 'grayD', 'grayVL', 'grayL', 'outline', _, _, _, _, _, _, _],
/* row 15 */ [_, _, _, _, _, 'outline', 'bodyD', 'bodyD', 'outline', 'shellM', 'bellyM', 'bellyM', 'grayD', 'grayD', 'teal', 'grayD', 'grayD', 'outline', _, _, _, _, _, _, _],
/* row 16 */ [_, _, _, _, _, 'outline', 'bodyD', 'bodyD', 'outline', 'shellM', 'bellyM', 'bellyM', 'grayD', 'grayD', 'teal', 'grayD', 'grayD', 'outline', _, _, _, _, _, _, _],
/* row 17 */ [_, _, _, _, _, _, 'outline', 'outline', _, 'gray', 'outline', 'grayD', 'bodyL', 'teal', 'teal', 'outline', 'outline', _, _, _, _, _, _, _, _],
/* row 18 */ [_, _, _, _, _, _, _, _, _, _, _, 'outline', 'teal', 'bodyD', 'teal', 'outline', 'outline', _, _, _, _, _, _, _, _],
/* row 19 */ [_, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _],
]

export const SLEEP_COLORS = {
  outline: '#191919',
  body: '#314F4F',
  bodyL: '#565656',
  bodyD: '#8F5128',
  belly: '#40736C',
  shadow: '#B86725',
  accent: '#9A8453',
  highlight: '#CF8427',
  detail1: '#529695',
  detail2: '#C9A859',
  detail3: '#6DB7D0',
  detail4: '#70C2F4',
  detail5: '#BBBBB9',
  detail6: '#9DD2F4',
  detail7: '#FFFFFF',
}

// grid: 24×20
export const SLEEP_BODY = [
/* row  0 */ [_, _, _, _, 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, 'outline', 'outline', _, _, _, _, _, _, _],
/* row  1 */ [_, _, 'outline', 'outline', 'detail1', 'detail4', 'detail4', 'detail4', 'outline', 'outline', 'outline', _, _, 'outline', _, 'outline', _, _, _, _, _, _, _, _],
/* row  2 */ [_, 'outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'detail1', 'outline', _, 'outline', _, _, _, _, _, _, _, _, _, _],
/* row  3 */ [_, 'outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'detail1', 'outline', _, 'outline', 'outline', _, _, _, _, _, _, _, _, _],
/* row  4 */ [_, 'outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'outline', _, _, _, _, _, _, _, _, _, _, _, _],
/* row  5 */ ['outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _],
/* row  6 */ ['outline', 'detail1', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'bodyL', 'highlight', 'shadow', 'outline', 'outline', _, _, _, _, _, _, _],
/* row  7 */ ['outline', 'detail1', 'detail4', 'detail4', 'detail4', 'detail4', 'detail1', 'detail4', 'outline', 'belly', 'detail1', 'detail1', 'bodyL', 'highlight', 'highlight', 'bodyD', 'highlight', 'outline', _, _, 'outline', 'outline', 'outline', _],
/* row  8 */ [_, 'outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'outline', 'detail4', 'detail1', 'detail1', 'bodyL', 'detail5', 'bodyD', 'bodyD', 'shadow', 'shadow', 'highlight', 'outline', 'outline', 'detail4', 'detail4', 'detail4', 'outline'],
/* row  9 */ [_, 'body', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail6', 'detail1', 'body', 'bodyL', 'detail2', 'bodyL', 'detail7', 'highlight', 'highlight', 'highlight', 'shadow', 'outline', 'detail6', 'detail4', 'detail1', 'detail1', 'detail6'],
/* row 10 */ [_, 'outline', 'detail4', 'detail4', 'detail4', 'detail1', 'detail4', 'detail4', 'detail1', 'bodyL', 'bodyL', 'detail2', 'bodyL', 'detail7', 'highlight', 'highlight', 'highlight', 'shadow', 'outline', 'detail4', 'detail4', 'bodyL', 'bodyL', 'detail4'],
/* row 11 */ [_, _, 'outline', 'outline', 'outline', 'outline', 'bodyL', 'bodyL', 'outline', 'accent', 'detail2', 'detail4', 'detail1', 'bodyL', 'detail7', 'highlight', 'highlight', 'bodyD', 'shadow', 'outline', 'detail1', 'detail4', 'detail4', 'detail1'],
/* row 12 */ [_, _, 'outline', 'outline', 'detail4', 'detail4', 'outline', 'detail2', 'detail1', 'detail3', 'detail4', 'detail4', 'detail1', 'bodyL', 'detail5', 'bodyD', 'bodyD', 'bodyD', 'shadow', 'outline', 'bodyL', 'detail1', 'detail1', 'detail1'],
/* row 13 */ [_, _, _, _, 'outline', 'detail4', 'bodyL', 'bodyL', 'detail4', 'detail4', 'detail4', 'detail1', 'bodyL', 'detail2', 'bodyL', 'detail5', 'detail5', 'bodyD', 'bodyD', 'outline', 'detail1', 'belly', 'belly', 'outline'],
/* row 14 */ [_, _, 'outline', 'outline', 'belly', 'outline', 'belly', 'outline', 'detail1', 'body', 'outline', 'outline', 'detail2', 'belly', 'belly', 'bodyL', 'bodyL', 'detail5', 'outline', 'belly', 'outline', 'outline', 'outline', _],
/* row 15 */ [_, _, 'outline', 'outline', 'belly', 'belly', 'belly', 'belly', 'outline', 'accent', 'detail2', 'bodyL', 'detail1', 'detail4', 'belly', 'belly', 'belly', 'bodyL', 'outline', 'outline', _, _, _, _],
/* row 16 */ [_, _, 'outline', 'outline', 'belly', 'belly', 'belly', 'belly', 'outline', 'detail2', 'detail2', 'bodyL', 'detail1', 'detail4', 'belly', 'belly', 'belly', 'bodyL', 'outline', 'outline', _, _, _, _],
/* row 17 */ [_, _, _, _, 'outline', 'outline', 'outline', 'outline', _, 'bodyL', 'outline', 'belly', 'belly', 'detail1', 'belly', 'belly', 'belly', 'outline', _, _, _, _, _, _],
/* row 18 */ [_, _, _, _, _, _, _, _, _, _, _, 'outline', 'belly', 'belly', 'belly', 'outline', 'outline', _, _, _, _, _, _, _],
/* row 19 */ [_, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _],
]