// 거북왕(Blastoise) — pixel art (auto-converted from 32×24)
const _ = null

export const COLORS = {
  outline: '#191919',
  body: '#313131',
  bodyL: '#6B4A29',
  bodyD: '#525252',
  belly: '#3A638C',
  shadow: '#8C633A',
  accent: '#7B7B7B',
  highlight: '#527BAD',
  detail1: '#B5844A',
  detail2: '#CEB552',
  detail3: '#7BADEF',
  detail4: '#BDBDB5',
  detail5: '#F7E694',
  detail6: '#FFFFFF',
}

// grid: 32×29
export const BASE_BODY = [
/* row  0 */ [_, _, _, _, _, _, _, _, 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  1 */ [_, _, _, _, _, _, 'outline', 'outline', 'accent', 'detail4', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  2 */ [_, _, _, _, _, _, 'outline', 'body', 'accent', 'detail4', 'body', 'outline', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  3 */ [_, _, _, _, _, _, 'outline', 'body', 'detail4', 'detail4', 'detail4', 'detail4', 'outline', _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', _, _, _, _, _, _],
/* row  4 */ [_, _, _, _, _, _, 'outline', 'outline', 'accent', 'detail4', 'detail4', 'detail4', 'detail4', 'outline', _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'detail6', 'detail6', 'detail6', 'outline', _, _, _, _, _],
/* row  5 */ [_, _, _, _, _, _, _, _, 'outline', 'accent', 'detail4', 'detail4', 'shadow', 'bodyL', 'outline', 'outline', 'outline', 'outline', 'detail1', 'bodyL', 'bodyL', 'bodyD', 'detail6', 'body', 'body', 'body', 'detail6', 'outline', _, _, _, _],
/* row  6 */ [_, _, _, _, _, _, 'outline', 'outline', 'detail3', 'body', 'shadow', 'shadow', 'bodyL', 'detail1', 'detail1', 'bodyL', 'bodyL', 'detail1', 'bodyL', 'bodyD', 'bodyD', 'detail4', 'detail6', 'body', 'body', 'body', 'detail6', 'outline', _, _, _, _],
/* row  7 */ [_, _, _, _, _, _, 'outline', 'body', 'detail3', 'body', 'shadow', 'shadow', 'bodyL', 'detail1', 'detail1', 'bodyL', 'bodyL', 'detail1', 'bodyL', 'bodyD', 'bodyD', 'detail4', 'detail6', 'body', 'body', 'body', 'detail6', 'outline', _, _, _, _],
/* row  8 */ [_, _, _, _, _, 'outline', 'detail3', 'detail3', 'detail3', 'highlight', 'bodyD', 'bodyD', 'bodyD', 'detail1', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'bodyL', 'accent', 'accent', 'detail4', 'detail4', 'detail6', 'detail6', 'detail6', 'outline', _, _, _, _, _],
/* row  9 */ [_, _, _, _, _, 'outline', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'bodyD', 'detail3', 'detail3', 'detail3', 'bodyD', 'bodyL', 'accent', 'accent', 'accent', 'detail4', 'detail4', 'detail4', 'bodyD', 'detail1', 'outline', _, _, _, _],
/* row 10 */ [_, _, _, _, 'outline', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'belly', 'belly', 'bodyD', 'detail4', 'bodyL', 'bodyL', 'accent', 'accent', 'bodyL', 'bodyL', 'bodyL', 'detail1', 'outline', _, _, _, _],
/* row 11 */ [_, _, _, _, 'outline', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'belly', 'belly', 'bodyD', 'detail4', 'bodyL', 'bodyL', 'accent', 'accent', 'bodyL', 'bodyL', 'bodyL', 'detail1', 'outline', _, _, _, _],
/* row 12 */ [_, _, _, 'outline', 'body', 'highlight', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'body', 'detail3', 'detail3', 'belly', 'belly', 'bodyD', 'detail4', 'detail4', 'detail4', 'bodyL', 'bodyL', 'shadow', 'shadow', 'detail1', 'outline', _, _, _, _, _],
/* row 13 */ [_, 'outline', 'outline', 'highlight', 'highlight', 'body', 'detail3', 'detail3', 'highlight', 'detail3', 'body', 'body', 'detail6', 'highlight', 'detail3', 'detail3', 'detail3', 'bodyD', 'bodyD', 'detail4', 'detail4', 'detail4', 'bodyL', 'shadow', 'shadow', 'bodyL', 'shadow', 'outline', _, _, _, _],
/* row 14 */ [_, 'outline', 'body', 'highlight', 'bodyD', 'detail3', 'detail3', 'detail3', 'belly', 'body', 'shadow', 'shadow', 'detail6', 'highlight', 'detail2', 'highlight', 'highlight', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'detail4', 'bodyL', 'bodyL', 'shadow', 'shadow', 'outline', _, _, _, _],
/* row 15 */ ['outline', 'highlight', 'highlight', 'bodyD', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'belly', 'detail2', 'detail2', 'body', 'bodyD', 'bodyD', 'bodyD', 'highlight', 'highlight', 'highlight', 'bodyD', 'detail4', 'detail4', 'detail4', 'bodyL', 'bodyL', 'outline', 'outline', _, _],
/* row 16 */ ['outline', 'highlight', 'highlight', 'bodyD', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'highlight', 'detail2', 'detail2', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'highlight', 'highlight', 'highlight', 'bodyD', 'detail4', 'detail4', 'detail4', 'bodyL', 'bodyL', 'body', 'outline', _, _],
/* row 17 */ ['outline', 'detail4', 'detail4', 'highlight', 'bodyD', 'detail3', 'highlight', 'highlight', 'detail3', 'detail3', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'bodyD', 'detail2', 'bodyD', 'detail3', 'detail3', 'highlight', 'highlight', 'bodyD', 'bodyD', 'detail4', 'bodyL', 'shadow', 'body', 'outline', _, _],
/* row 18 */ [_, 'outline', 'outline', 'outline', _, 'outline', 'bodyD', 'bodyD', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'detail2', 'detail2', 'detail2', 'bodyD', 'highlight', 'detail3', 'detail3', 'detail3', 'highlight', 'bodyD', 'bodyD', 'detail4', 'detail4', 'shadow', 'body', 'body', 'outline', 'outline'],
/* row 19 */ [_, _, _, _, _, _, 'outline', 'body', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'detail3', 'detail3', 'highlight', 'highlight', 'detail3', 'bodyD', 'highlight', 'highlight', 'bodyD', 'detail4', 'bodyD', 'highlight', 'highlight', 'highlight', 'outline'],
/* row 20 */ [_, _, _, _, _, _, 'outline', 'body', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'detail3', 'detail3', 'highlight', 'highlight', 'detail3', 'bodyD', 'highlight', 'highlight', 'bodyD', 'detail4', 'bodyD', 'highlight', 'highlight', 'highlight', 'outline'],
/* row 21 */ [_, _, _, _, _, 'outline', 'belly', 'belly', 'body', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'detail5', 'body', 'bodyD', 'detail6', 'detail3', 'detail3', 'detail3', 'highlight', 'bodyD', 'highlight', 'highlight', 'bodyD', 'detail4', 'detail4', 'bodyD', 'bodyD', 'outline', _],
/* row 22 */ [_, _, _, _, _, 'outline', 'belly', 'belly', 'belly', 'bodyD', 'detail5', 'detail5', 'detail5', 'detail5', 'detail2', 'bodyD', 'bodyD', 'bodyD', 'detail4', 'detail6', 'detail6', 'bodyD', 'detail3', 'belly', 'belly', 'highlight', 'bodyD', 'detail4', 'outline', 'outline', _, _],
/* row 23 */ [_, _, _, _, _, _, 'outline', 'body', 'belly', 'belly', 'bodyD', 'bodyD', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'detail3', 'detail3', 'detail3', 'detail3', 'belly', 'highlight', 'outline', _, _, _, _],
/* row 24 */ [_, _, _, _, _, _, 'outline', 'outline', 'belly', 'belly', 'bodyD', 'bodyD', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'bodyD', 'bodyD', 'detail3', 'detail3', 'detail3', 'detail3', 'belly', 'highlight', 'outline', _, _, _, _],
/* row 25 */ [_, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'bodyD', 'detail5', 'detail5', 'detail5', 'detail5', 'detail2', 'bodyD', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'belly', 'highlight', 'outline', _, _, _, _],
/* row 26 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'detail2', 'detail2', 'detail2', 'detail2', 'bodyD', 'bodyD', 'detail3', 'detail3', 'belly', 'belly', 'highlight', 'outline', _, _, _, _, _],
/* row 27 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', 'detail6', 'highlight', 'highlight', 'highlight', 'detail4', 'outline', _, _, _, _, _],
/* row 28 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _],
]
// sleep/9-anims.js — pixel art (auto-converted from 32×29)

export const SLEEP_COLORS = {
  outline: '#191919',
  body: '#291B10',
  bodyL: '#1D3058',
  bodyD: '#373739',
  belly: '#553923',
  shadow: '#704D2D',
  accent: '#504E4F',
  highlight: '#3A5872',
  detail1: '#836448',
  detail2: '#6C6C6C',
  detail3: '#4B6E98',
  detail4: '#A77945',
  detail5: '#8292B3',
  detail6: '#CCB356',
  detail7: '#ADAEA6',
  detail8: '#77A7E7',
  detail9: '#D4D4D4',
  detail10: '#EBEAE6',
}

// grid: 32×29
export const SLEEP_BODY = [
/* row  0 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  1 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  2 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  3 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  4 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  5 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  6 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  7 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  8 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row  9 */ [_, _, _, _, _, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _],
/* row 10 */ [_, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'shadow', 'detail4', 'shadow', 'shadow', 'detail4', 'detail4', 'detail4', 'detail4', 'shadow', 'outline', _, _, _, _, _, _, _, _, _, _],
/* row 11 */ [_, _, _, 'outline', 'outline', 'outline', 'outline', 'shadow', 'shadow', 'detail4', 'detail4', 'detail1', 'detail4', 'detail4', 'detail4', 'detail4', 'shadow', 'shadow', 'detail4', 'detail4', 'detail4', 'detail4', 'outline', 'outline', _, _, _, _, _, _, _, _],
/* row 12 */ [_, _, _, 'outline', 'detail9', 'detail9', 'detail2', 'outline', 'shadow', 'detail4', 'outline', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'detail4', 'shadow', 'shadow', 'outline', 'outline', 'outline', 'detail4', 'outline', _, _, _, _, _, _, _, _],
/* row 13 */ [_, _, _, 'outline', 'detail7', 'detail7', 'outline', 'outline', 'shadow', 'outline', 'shadow', 'shadow', 'shadow', 'shadow', 'detail4', 'detail4', 'detail4', 'shadow', 'shadow', 'shadow', 'detail4', 'shadow', 'outline', 'shadow', 'outline', _, _, _, _, _, _, _],
/* row 14 */ [_, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'shadow', 'detail1', 'detail7', 'detail10', 'detail10', 'detail10', 'shadow', 'detail4', 'shadow', 'shadow', 'detail4', 'detail4', 'outline', 'detail4', 'shadow', 'outline', 'outline', _, _, _, _, _, _, _],
/* row 15 */ [_, _, _, _, _, 'outline', 'outline', 'detail5', 'outline', 'detail2', 'detail2', 'detail2', 'detail2', 'detail2', 'detail10', 'detail9', 'shadow', 'outline', 'shadow', 'outline', 'detail7', 'outline', 'detail4', 'outline', 'shadow', 'outline', _, _, _, _, _, _],
/* row 16 */ [_, _, _, _, _, 'outline', 'outline', 'detail3', 'detail8', 'detail8', 'detail3', 'detail8', 'detail3', 'detail2', 'outline', 'outline', 'detail10', 'shadow', 'outline', 'detail9', 'detail7', 'detail9', 'shadow', 'outline', 'belly', 'detail7', 'outline', 'outline', _, _, _, _],
/* row 17 */ [_, _, _, _, _, 'outline', 'outline', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'bodyL', 'detail8', 'detail5', 'detail9', 'detail10', 'outline', 'detail7', 'outline', 'detail7', 'shadow', 'body', 'belly', 'detail7', 'detail3', 'outline', _, _, _, _],
/* row 18 */ [_, _, _, _, 'outline', 'detail3', 'outline', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'bodyD', 'bodyD', 'detail7', 'detail10', 'outline', 'detail2', 'detail7', 'detail2', 'shadow', 'shadow', 'detail7', 'detail7', 'outline', _, _, _, _, _],
/* row 19 */ [_, _, _, _, 'outline', 'outline', 'detail3', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'bodyL', 'outline', 'detail7', 'detail10', 'outline', 'outline', 'outline', 'shadow', 'shadow', 'detail7', 'outline', 'outline', _, _, _, _, _],
/* row 20 */ [_, _, _, _, _, 'outline', 'detail3', 'detail8', 'detail8', 'detail8', 'detail3', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'outline', 'detail7', 'accent', 'accent', 'detail10', 'detail10', 'belly', 'detail7', 'outline', 'detail3', 'outline', _, _, _, _, _],
/* row 21 */ [_, _, _, _, _, 'outline', 'outline', 'detail8', 'detail8', 'detail3', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'outline', 'detail7', 'detail3', 'detail3', 'accent', 'detail10', 'detail7', 'detail7', 'detail3', 'outline', _, _, _, _, _, _],
/* row 22 */ [_, _, _, _, _, 'outline', 'detail8', 'detail8', 'detail8', 'detail8', 'detail3', 'outline', 'outline', 'detail8', 'detail3', 'detail8', 'outline', 'highlight', 'detail8', 'detail8', 'detail3', 'accent', 'outline', 'detail3', 'outline', 'outline', _, _, _, _, _, _],
/* row 23 */ [_, _, _, _, _, 'outline', 'outline', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail8', 'detail6', 'detail3', 'detail3', 'detail8', 'highlight', 'detail8', 'detail3', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _],
/* row 24 */ [_, _, _, _, _, _, _, 'outline', 'detail3', 'detail3', 'detail3', 'detail3', 'detail3', 'detail6', 'outline', 'detail3', 'highlight', 'detail8', 'detail3', 'highlight', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _],
/* row 25 */ [_, _, _, _, _, _, _, _, 'outline', 'outline', 'outline', 'outline', 'outline', 'outline', _, 'outline', 'outline', 'outline', 'outline', 'outline', _, _, _, _, _, _, _, _, _, _, _, _],
/* row 26 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row 27 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
/* row 28 */ [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _],
]
